### ISSUE TITLE
Only seems to get DMs from slackbot

### ISSUE THREAD

**Issue by tdcox** [zach-snell/slack-export#4]
```
➜ python slack_export.py --token REDACTED --directMessages --zip slack_export_all_DMs
Successfully authenticated for team REDACTED and user REDACTED
Found 462 Users
Found 74 Public Channels
Found 4 Private Channels or Group DMs
Found 76 1:1 DM conversations

Making channels file
Fetching 1:1 DMs with slackbot
➜ 
```

Expected behaviour: To iterate through the list of DM conversations, downloading each.

I see a similar problem if I use `--prompt` and select a number of conversations - only one seems to be downloaded.

**Comment by zach-snell** [comment]
Resolved by PR: https://github.com/zach-snell/slack-export/pull/3#pullrequestreview-166776784
